services:
  postgres:
    image: 'postgres:latest'
    container_name: carebridge_postgres
    env_file: "env.properties"
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
