services:
  postgres:
    image: 'postgres:latest'
    container_name: carebridge
    env_file: "env.properties"
    restart: unless-stopped
    environment:
      POSTGRES_DB: carebridge_db
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "5433:5432"
  mongodb:
    image: 'mongo:latest'
    container_name: carebridge-mongodb
    env_file: "env.properties"
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: chat_db
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    ports:
      - "27017:27017"
