spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/carebridge_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:dbpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.config.import=optional:file:.env

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/chat_db}
spring.data.mongodb.database=chat_db

server.port=${PORT:8443}
server.ssl.enabled=false

app.security.allowed-origins=${ALLOWED_ORIGINS:http://localhost:*}

app.security.jwt.expiration-hours=24
app.security.jwt.inactivity-minutes=15

app.security.cookie.http-only=true
app.security.cookie.secure=${COOKIE_SECURE:false}
app.security.cookie.same-site=${COOKIE_SAME_SITE:Lax}
app.security.cookie.path=/
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000
spring.mail.protocol=smtp
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.debug=true

spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false

logging.level.com.carebridge.backend.password=${LOG_LEVEL:INFO}
logging.level.com.carebridge.backend.security=${LOG_LEVEL:INFO}
logging.level.org.springframework.mail=${LOG_LEVEL:INFO}
logging.level.org.springframework.mail.javamail=${LOG_LEVEL:INFO}

